{{ config(materialized='table') }}

SELECT SHA2(SHIPPING_SERVICE, 512) AS SHIPPING_SERVICE_PK
     , SHIPPING_SERVICE
FROM {{ ref('stg_orders') }}
WHERE SHIPPING_SERVICE != NULL
GROUP BY SHIPPING_SERVICE
UNION
SELECT SHA2(-1, 512) AS SHIPPING_SERVICE_PK
     , 'Unknown' AS SHIPPING_SERVICE
