{{ config(materialized='table') }}

SELECT SHA2(PROMO_ID, 512) AS PROMO_PK
     , DISCOUNT
     , STATUS
--FROM DEV_DB.DBT_REEVESSMITHIIIGMAILCOM.STG_PROMOS
FROM {{ ref('stg_promos') }}
WHERE PROMO_ID IS NOT NULL
UNION
SELECT SHA2(-1, 512) AS PROMO_PK
     , NULL AS DISCOUNT
     , 'Unknown' AS STATUS