{{ config(materialized='table') }}

SELECT SHA2(COALESCE(ORDER_ID, '-1'), 512) AS ORDER_PK
     , SHA2(COALESCE(USER_ID, '-1'), 512) AS USER_PK
     , SHA2(COALESCE(PROMO_ID, '-1'), 512) AS PROMO_PK
     , SHA2(COALESCE(ADDRESS_ID, '-1'), 512) AS ADDRESS_PK
     , SHA2(COALESCE(STATUS, '-1'), 512) AS ORDER_STATUS_PK
     , SHA2(COALESCE(SHIPPING_SERVICE, '-1'), 512) AS SHIPPING_SERVICE_PK
     , REPLACE(CREATED_AT::DATE::VARCHAR, '-', '')::NUMBER AS ORDER_DATE_ID
     , ORDER_COST
     , SHIPPING_COST
     , ORDER_TOTAL
     , TRACKING_ID
     , ESTIMATED_DELIVERY_AT
     , DELIVERED_AT
FROM {{ ref('stg_orders') }}