{{ config(materialized='table') }}

WITH
CTE_SESSION AS
(
    SELECT SESSION_ID
    FROM {{ ref('stg_events') }}
    GROUP BY SESSION_ID
)
,
CTE_PAGE_VIEW AS
(
    SELECT SESSION_ID
         , TRUE AS PAGE_VIEW
    FROM {{ ref('stg_events') }}
    WHERE EVENT_TYPE = 'page_view'
    GROUP BY SESSION_ID
)
,
CTE_ADD_TO_CART AS
(
    SELECT SESSION_ID
         , TRUE AS ADD_TO_CART
    FROM {{ ref('stg_events') }}
    WHERE EVENT_TYPE = 'add_to_cart'
    GROUP BY SESSION_ID
)
,
CTE_CHECKOUT AS
(
    SELECT SESSION_ID
         , TRUE AS CHECKOUT
    FROM {{ ref('stg_events') }}
    WHERE EVENT_TYPE = 'checkout'
    GROUP BY SESSION_ID
)
SELECT T1.SESSION_ID
     , COALESCE(T2.PAGE_VIEW, FALSE) AS PAGE_VIEW
     , COALESCE(T3.ADD_TO_CART, FALSE) AS ADD_TO_CART
     , COALESCE(T4.CHECKOUT, FALSE) AS CHECKOUT
FROM CTE_SESSION T1
LEFT
JOIN CTE_PAGE_VIEW T2 ON T1.SESSION_ID = T2.SESSION_ID
LEFT
JOIN CTE_ADD_TO_CART T3 ON T1.SESSION_ID = T3.SESSION_ID
LEFT
JOIN CTE_CHECKOUT T4 ON T1.SESSION_ID = T4.SESSION_ID
