{{ config(materialized='table') }}

SELECT SHA2(EVENT_ID, 512) AS EVENT_PK
     , SHA2(SESSION_ID, 512) AS SESSION_PK
     , SHA2(USER_ID, 512) AS USER_PK
     , SHA2(ORDER_ID, 512) AS ORDER_PK
     , SHA2(PRODUCT_ID, 512) AS PRODUCT_PK
     , PAGE_URL
     , CREATED_AT
-- FROM DEV_DB.DBT_REEVESSMITHIIIGMAILCOM.STG_EVENTS
FROM {{ ref('stg_events') }}
WHERE EVENT_TYPE = 'page_view'